// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgW_jm73bRZcItB9ZfQMIW7pf0IpjEC1E',
    appId: '1:114401789138:web:6b6825b139a49d57b5190b',
    messagingSenderId: '114401789138',
    projectId: 'none14',
    authDomain: 'none14.firebaseapp.com',
    storageBucket: 'none14.appspot.com',
    measurementId: 'G-JMBKMRWNY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg3sCWgWW6FzotYxG1LGW7u7Y_j9wjKF4',
    appId: '1:114401789138:android:98b7265da25a1bdbb5190b',
    messagingSenderId: '114401789138',
    projectId: 'none14',
    storageBucket: 'none14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5ZKVKhXMZtSrZ0quKY3KSqxhMWfEj44',
    appId: '1:114401789138:ios:3ea6e1655ba41784b5190b',
    messagingSenderId: '114401789138',
    projectId: 'none14',
    storageBucket: 'none14.appspot.com',
    iosClientId: '114401789138-30pmd0gm95qflb94gor6pmdp6gfmipfi.apps.googleusercontent.com',
    iosBundleId: 'flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE5ZKVKhXMZtSrZ0quKY3KSqxhMWfEj44',
    appId: '1:114401789138:ios:2260a93837ab66ddb5190b',
    messagingSenderId: '114401789138',
    projectId: 'none14',
    storageBucket: 'none14.appspot.com',
    iosClientId: '114401789138-78mng2ugat438c183ggadrl51c4spt17.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
